server:
  port: 7901
user:
  userServicePath: http://localhost:7900/user/info/

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: movie-service
